#!/bin/bash
# Generate README.md Helper Script
# Creates or updates a comprehensive README with repository information

set -e  # Exit on error

echo "📝 Generating README.md..."

# Get repository information
REPO_NAME=$(git rev-parse --show-toplevel | xargs basename)
REPO_URL=$(git config --get remote.origin.url)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
COMMIT_COUNT=$(git rev-list --count HEAD)
LAST_COMMIT=$(git log -1 --pretty=format:"%h - %s (%ar)")

# Create README.md
cat > README.md << EOF
# $REPO_NAME

Repository for managing and pushing code changes with automatic documentation and synchronization.

## Repository Information

- **Repository**: $REPO_URL
- **Current Branch**: $BRANCH
- **Total Commits**: $COMMIT_COUNT
- **Last Commit**: $LAST_COMMIT

## Project Structure

\`\`\`
.
├── .github/
│   └── skills/
│       └── push-to-repo/          # Push skill with helper scripts
│           ├── SKILL.md            # Skill documentation
│           └── scripts/
│               ├── push-to-repo.sh # Main push automation script
│               └── generate-readme.sh  # README generation script
├── 23052026/
│   └── Task1_TestPlan.md           # Test planning documentation
├── .vscode/
│   └── settings.json               # VS Code settings
└── README.md                        # This file
\`\`\`

## Quick Start

### Push Code with Automatic README Generation

Run the main push script to automatically:
- Generate/update this README
- Commit changes
- Sync with remote branch
- Push to GitHub

\`\`\`bash
./.github/skills/push-to-repo/scripts/push-to-repo.sh
\`\`\`

Or with a specific branch:
\`\`\`bash
./.github/skills/push-to-repo/scripts/push-to-repo.sh main
\`\`\`

### Manual Steps

1. **Generate README**:
   \`\`\`bash
   ./.github/skills/push-to-repo/scripts/generate-readme.sh
   \`\`\`

2. **Commit Changes**:
   \`\`\`bash
   git add .
   git commit -m "Update: generated README and other changes"
   \`\`\`

3. **Push to Remote**:
   \`\`\`bash
   git fetch origin
   git pull origin $BRANCH --rebase
   git push origin $BRANCH
   \`\`\`

## Usage Guide

### Push Changes with README Generation

The recommended approach is to use the automated push script:

\`\`\`bash
./.github/skills/push-to-repo/scripts/push-to-repo.sh [branch-name]
\`\`\`

**What the script does:**
1. Checks for uncommitted changes and stashes if needed
2. Generates or updates README.md automatically
3. Commits the README changes
4. Fetches latest changes from remote
5. Rebases local commits on remote branch
6. Pushes all changes to GitHub
7. Restores any stashed changes

### Handling Merge Conflicts

If conflicts occur during rebase:

1. **View conflicts**:
   \`\`\`bash
   git status
   \`\`\`

2. **Resolve conflicts** in your editor

3. **Continue rebase**:
   \`\`\`bash
   git add .
   git rebase --continue
   \`\`\`

4. **Push when resolved**:
   \`\`\`bash
   git push origin $BRANCH
   \`\`\`

## Features

✨ **Automatic README Generation**
- Keeps README synchronized with repository state
- Includes commit history and branch information
- Updates on every push

🔄 **Smart Sync**
- Automatic rebasing for clean history
- Handles merge conflicts gracefully
- Prevents non-fast-forward errors

📦 **Stash Management**
- Automatically stashes uncommitted changes
- Restores changes after successful push
- Zero data loss workflow

## Recent Activity

| Commit | Message | Date |
|--------|---------|------|
| $LAST_COMMIT | - | - |

## Resources

- [Git Documentation](https://git-scm.com/doc)
- [Git Rebase Guide](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)
- [GitHub Push Guide](https://docs.github.com/en/github/using-git/pushing-commits-to-a-remote-repository)

---

**Last Updated**: $(date)
**Generated by**: push-to-repo skill automation
EOF

echo "✅ README.md generated successfully"
